export function createAppState() {
  return {
    containers: [],
    originalContainers: [],
    houses: [],
    coverage: null,
    places: [],
    placesById: new Map(),
    activePlace: null,
    placeLoadStatus: 'idle',
    placeSelectionId: 0,
    addressIndex: [],
    addressIndexPlaceId: null,
    addressIndexByPlaceId: new Map(),
    houseDetailBundlesByPlaceId: new Map(),
    containersById: new Map(),
    containersByKey: new Map(),
    originalContainersById: new Map(),
    originalContainersByKey: new Map(),
    activeContainerIndex: null,
    activeContainerKey: null,
    selectedHouse: null,
    coverageCircle: null,
    selectedHouseMarker: null,
    containerMarkers: [],
    containerButtons: [],
    liveRouteCache: new Map(),
    houseSelectionId: 0,
    containerInfoCollapsed: false,
    houseInfoCollapsed: false,
    containerEditorExpanded: false,
    addContainerMode: false,
    pendingNewContainer: null,
    editingContainerKey: null,
    nextContainerClientKey: 1,
    unlockedContainerKey: null,
    containerDragStart: null,
    suppressContainerClickUntil: 0
  };
}
